---
applications:
- name: spring-boot-web-spring-security
  memory: 512M
  buildpack: java_buildpack
  routes:
  - route: spring-boot-web-spring-security.cfapps.io
# config context path to "/" by setting an empty string
Server:
  contextPath:

# JACKSON
Spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

#logging:
#  level:
#    org.springframework:
#      security: DEBUG