INSERT INTO USER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, ADDRESS, EMAIL, MOBILENO) VALUES (1, 'admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin', 'admin','chennai', 'admin@admin.com', '9176731407');
INSERT INTO USER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, ADDRESS, EMAIL, MOBILENO) VALUES (2, 'user', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'user', 'user','chennai', 'enabled@user.com',  '9176731407');
INSERT INTO USER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, ADDRESS, EMAIL, MOBILENO) VALUES (3, 'disabled', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user', 'user','chennai', 'disabled@user.com', '9176731407');

INSERT INTO AUTHORITY (ID, NAME) VALUES (1, 'ROLE_USER');
INSERT INTO AUTHORITY (ID, NAME) VALUES (2, 'ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (1, 1);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (2, 1);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (3, 1);
