DROP TABLE USER;
DROP TABLE USER_AUTHORITY;
DROP TABLE AUTHORITY;


CREATE TABLE AUTHORITY (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(30)
  
);


CREATE TABLE USER_AUTHORITY (
  USER_ID   INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  AUTHORITY_ID    INT(4)
  
);

CREATE TABLE USER (
  ID        INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  USERNAME   VARCHAR(30),
  PASSWORD   VARCHAR(100),
  FIRSTNAME VARCHAR(30),
  LASTNAME VARCHAR(30),
  ADDRESS VARCHAR(100),
  EMAIL   VARCHAR(30),
  MOBILENO VARCHAR(10)
 
  
);


