DROP TABLE AUTHORITY IF EXISTS;
DROP TABLE USER_AUTHORITY IF EXISTS;
DROP TABLE USER IF EXISTS;


CREATE TABLE AUTHORITY (
  ID         INTEGER IDENTITY PRIMARY KEY,
  NAME VARCHAR(30)
  
);


CREATE TABLE USER_AUTHORITY (
  USER_ID         INTEGER IDENTITY PRIMARY KEY,
  AUTHORITY_ID    INTEGER
  
);

CREATE TABLE USER (
  ID         INTEGER IDENTITY PRIMARY KEY,
  USERNAME   VARCHAR(30),
  PASSWORD   VARCHAR(30),
  FIRSTNAME VARCHAR(30),
  LASTNAME VARCHAR_IGNORECASE(30),
  EMAIL   VARCHAR(30),
  ENABLED   INTEGER,
  LASTPASSWORDRESETDATE    DATE
  
);


